FROM node:20

RUN apt-get update && apt-get install -y python3 python3-dev python3-pip make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 5173

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
